---

-
  name: configure Load Balancer
  hosts: all
  tasks:
     - name: Execute command 'sudo apt update'
       command: sudo apt update
     - name: Execute command 'sudo apt install yum'
       command: sudo apt -y install yum
